language: node_js
node_js:
    - "5.7.0"
script:
    - "easy_install pip"
    - "pip install yotta"
    - "yotta target bbc-microbit-classic-gcc"
    - "npm install -g pxt"
    - "pxt target microbit"
    - "pxt install"
    - "pxt build"
sudo: false
cache:
    directories:
    - npm_modules
    - pxt_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libusb-1.0-0-dev
      - cmake 
      - build-essential 
      - ninja-build 
      - python-dev 
      - libffi-dev 
      - libssl-dev
      - python-setuptools
env:
  - PXT_ENV=production CXX=g++-4.8